### ISSUE TITLE
Crash on first run

### ISSUE THREAD

**Issue by carnager** [thesquelched/suggestive#11]
```
carnager@caprica ~/suggestive > suggestive -u
Traceback (most recent call last):
  File "/usr/bin/suggestive", line 9, in <module>
    load_entry_point('suggestive==0.4.2', 'console_scripts', 'suggestive')()
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/app.py", line 590, in main
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/app.py", line 570, in run
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/app.py", line 222, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/app.py", line 52, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/app.py", line 96, in initialize_buffers
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/app.py", line 113, in create_playlist_buffer
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/playlist.py", line 475, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/playlist.py", line 90, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/playlist.py", line 220, in update_model
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/playlist.py", line 191, in track_models
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/playlist.py", line 165, in playlist_tracks
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/mstat.py", line 143, in database_tracks_from_mpd
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.2-py3.5.egg/suggestive/mstat.py", line 143, in <listcomp>
KeyError: 'flac/Spectres/2016 Utopia/01-New Buildings.flac'
```

**Comment by thesquelched** [comment]
Shot in the dark here: do you already have tracks in your mpd playlist, perhaps via another MPD client?

**Comment by carnager** [comment]
indeed, with empty playlist it works

**Comment by thesquelched** [comment]
I don't see the initialization message in your output, so it has to be piggybacking on an existing music database.  In that case, the MPD database could have been updated before your most recently `suggestive` run, which would mean that the MPD database has items that the suggestive database does not, leading to this error.

I'm testing a fix now that detects this and attempts to sync the databases, falling back on mocked-out database items if that fails.  I should have it up later today.
