### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by carnager** [thesquelched/suggestive#7]
When starting up suggestive it crashes with a KeyError.

```
carnager@caprica ~/suggestive/suggestive > suggestive             
Traceback (most recent call last):
  File "/usr/bin/suggestive", line 9, in <module>
    load_entry_point('suggestive==0.4.0', 'console_scripts', 'suggestive')()
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 586, in main
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 566, in run
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 223, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 53, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 97, in initialize_buffers
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 114, in create_playlist_buffer
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 471, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 90, in __init__
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 220, in update_model
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 191, in track_models
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 165, in playlist_tracks
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 140, in database_tracks_from_mpd
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 140, in <listcomp>
KeyError: 'flac/Motorpsycho/1993 Demon Box/CD 1/01-Waiting for the One.flac'
```

**Comment by gregf** [comment]
Having the same issue.

```
Traceback (most recent call last):
  File "/usr/local/bin/suggestive", line 9, in <module>
    load_entry_point('suggestive==0.4.0', 'console_scripts', 'suggestive')()
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 586, in main
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 566, in run
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 223, in __init__
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 53, in __init__
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 97, in initialize_buffers
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 114, in create_playlist_buffer
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 471, in __init__
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 90, in __init__
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 220, in update_model
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 191, in track_models
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/playlist.py", line 165, in playlist_tracks
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 140, in database_tracks_from_mpd
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 140, in <listcomp>
KeyError: 'p/Pearl Jam/Rearviewmirror Greatest Hits 1991–2003/02 Alive.flac'
```

**Comment by thesquelched** [comment]
Can you backup your `music.db` file in your conf directory (usually `$HOME/.suggestive`) and try running it again?  I'm wondering if this is happening on initialization or subsequent runs.

**Comment by thesquelched** [comment]
Sorry, you have to delete the `music.db` file after backing it up.

**Comment by thesquelched** [comment]
Also, how big is your current playlist? You can open another mpd app like ncmpcpp to check.

**Comment by gregf** [comment]
@thesquelched After backing up and moving music.db it appeared to be working at first then I got this.

```
Traceback (most recent call last):
  File "/usr/local/bin/suggestive", line 9, in <module>
    load_entry_point('suggestive==0.4.0', 'console_scripts', 'suggestive')()
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 586, in main
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/app.py", line 554, in run
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 755, in update_mpd
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 518, in load
  File "/usr/local/lib/python3.5/dist-packages/suggestive-0.4.0-py3.5.egg/suggestive/mstat.py", line 459, in check_duplicates
  File "/usr/local/lib/python3.5/dist-packages/python_mpd2-0.5.5-py3.5.egg/mpd.py", line 629, in decorator
  File "/usr/local/lib/python3.5/dist-packages/python_mpd2-0.5.5-py3.5.egg/mpd.py", line 252, in _execute
  File "/usr/local/lib/python3.5/dist-packages/python_mpd2-0.5.5-py3.5.egg/mpd.py", line 279, in _write_command
  File "/usr/local/lib/python3.5/dist-packages/python_mpd2-0.5.5-py3.5.egg/mpd.py", line 259, in _write_line
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```

The first few runs I had to create a config file. It might be screwing up the import if the config file is missing on the first run.

According to mpd I have 21879 songs in my database.

**Comment by thesquelched** [comment]
@gregf interesting.  You shouldn't even be able to run it without a conf file (you should get an error like `Could not determine LastFM API key; see https://github.com/thesquelched/suggestive#configuration`)

**Comment by thesquelched** [comment]
Can you pull down the `mpd_track_key_error` branch and give that a shot?  I think the issue might be that the track list is getting modified in the middle of that function execution.

**Comment by carnager** [comment]
deleting music.db seems to work. it's initializing right now. Seems suggestive is creating a music.db file even if no config is present. probably should catch that

**Comment by thesquelched** [comment]
Strange that both of you are getting mpd connection errors, but maybe you just have much larger MPD databases than me and are seeing a timeout that I'm not.  Anyway, I'll add connection retry logic to the affected functions.

**Comment by thesquelched** [comment]
Branch updated; give it a shot

**Comment by carnager** [comment]
still not working, but with added error :)

```
carnager@caprica ~/suggestive > suggestive 
Music database not found; initializing...
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/mstat.py", line 34, in wrapper
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/mstat.py", line 467, in check_duplicates
  File "/usr/lib/python3.5/site-packages/mpd.py", line 600, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/usr/lib/python3.5/site-packages/mpd.py", line 238, in _execute
    return retval()
  File "/usr/lib/python3.5/site-packages/mpd.py", line 595, in decorator
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/mpd.py", line 406, in _fetch_songs
    return self._fetch_objects(["file"])
  File "/usr/lib/python3.5/site-packages/mpd.py", line 394, in _fetch_objects
    return self._wrap_iterator(self._read_objects(delimiters))
  File "/usr/lib/python3.5/site-packages/mpd.py", line 358, in _wrap_iterator
    return list(iterator)
  File "/usr/lib/python3.5/site-packages/mpd.py", line 316, in _read_objects
    for key, value in self._read_pairs():
  File "/usr/lib/python3.5/site-packages/mpd.py", line 295, in _read_pairs
    pair = self._read_pair(separator)
  File "/usr/lib/python3.5/site-packages/mpd.py", line 286, in _read_pair
    line = self._read_line()
  File "/usr/lib/python3.5/site-packages/mpd.py", line 271, in _read_line
    raise ConnectionError("Connection lost while reading line")
mpd.ConnectionError: Connection lost while reading line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/suggestive", line 9, in <module>
    load_entry_point('suggestive==0.4.1', 'console_scripts', 'suggestive')()
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/app.py", line 590, in main
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/app.py", line 558, in run
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/mstat.py", line 770, in update_mpd
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/mstat.py", line 533, in load
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/mstat.py", line 38, in wrapper
AttributeError: 'MpdLoader' object has no attribute 'conf'
```

**Comment by carnager** [comment]
carnager@caprica ~/Rips > mpc stats
Artists:   2154
Albums:    3573
Songs:    43235

**Comment by thesquelched** [comment]
Holy shit, I have no idea how you guys have such huge libraries. Well, I have some idea (hello, bittorrent!)

That error was a QA failure on my part.  Branch updated with bugfix and ... gasp... TESTS

**Comment by thesquelched** [comment]
By the way, I really appreciate you guys helping me out here.  I wasn't aware that anyone else was even using this.  This was sort of a learning experience for me when I originally wrote it, and there's a lot I should do WRT performance, UX, etc, so I hope you'll stick with it!

**Comment by gregf** [comment]
That fixed it for me. Thanks!

**Comment by carnager** [comment]
@thesquelched believe it or not, it's all original CDs in my case :) Let's say I am a freak.

**Comment by thesquelched** [comment]
I believe that's what happens when you don't visit the URL and authorize the application with the lastfm API before hitting enter.

**Comment by carnager** [comment]
i did though :)

**Comment by thesquelched** [comment]
I wonder if there's anything relevant in the logs? Look for `log.txt` in your conf directory (by default, `$HOME/.suggestive`).  FYI, when errors appear in the console like that, you can get the stack trace without the junk in the log file.

So the flow for initializing lastfm is basically:

1. Get auth token from lastfm API
2. Display URL (and attempt to open in browser) for lastfm page to authorize application
3. User clicks "Yes, Allow Access" (I think that's what the buttons says) on said lastfm page to authorize the application. The page should then indicate that the application was authorized
4. Back in suggestive, user hits a key
5. Lastfm client checks with API as to whether the auth token was authorized on that webpage

The only way that flow breaks is if 1) the button on the lastfm webpage wasn't hit or b) lastfm's API broke (it happens more than you'd expect).  You could try removing the session file `{conf_dir}/session` and then re-launching suggestive, which will force re-authorization.

**Comment by carnager** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/suggestive-0.4.1-py3.5.egg/suggestive/lastfm.py", line 92, in _initialize_client
    client.authenticate()
  File "/usr/lib/python3.5/site-packages/pylastfm-0.2.0-py3.5.egg/pylastfm/client.py", line 229, in authenticate
    session_key = self._auth.session_key()
  File "/usr/lib/python3.5/site-packages/pylastfm-0.2.0-py3.5.egg/pylastfm/auth.py", line 158, in session_key
    self._session_key))
pylastfm.error.FileError: Invalid/missing session key file: /home/carnager/.suggestive/session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pylastfm-0.2.0-py3.5.egg/pylastfm/client.py", line 275, in _request
    resp.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://ws.audioscrobbler.com/2.0/?api_key=70fe3a5747a0fda0e8575e5fa69546a2&method=auth.getSession&token=4ca0d7ff9ade6526767cf6d10624dfd4&format=json&api_sig=f9263c9128deb0870d7f1b07ff5de52a
```

**Comment by thesquelched** [comment]
Hmm... lastfm API returns a 403 error if the application wasn't authorized, so you're doing the right thing.  The only way I've been able to cause a 400 error is if there's a typo in the api secret; can you check the value in your config of the `api_secret` option in the `lastfm` section?  Make sure it matches the value shown in the `Your API Accounts` section of (the LastFM API site)[http://www.last.fm/api] when you click on the corresponding account.  You should see, in a yellow box at the top of the page, `Secret: is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`.

**Comment by carnager** [comment]
sorry, shouldnt have edited the comment. it was indeed the api secret

**Comment by thesquelched** [comment]
OK, cool.  Was there a typo, or did you not have it in the config?  Maybe I should make it clearer in the `README` that the secret is required.

**Comment by carnager** [comment]
It was completely missing

**Comment by thesquelched** [comment]
Oh, stupid me, I said it was optional.  I'll change that in the readme for now, and then I'll work on making it *actually* optional.  Thanks for your help!
